name: リリースの自動作成
on:
  pull_request:
    branches:
      - main
    types: [open, closed]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Return release version
        uses: actions/github-script@v2
        id: return_release_version
        with:
          result-encoding: string
          script: |
            console.log(github.ref)
            console.log(github.event.pull_request)
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.pull_request.ref }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}