name: リリースの自動作成
on:
  push:
    branches:
      - "release/**"
  pull_request:
    branches:
      - main
    types: [closed, opened]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Return release version
        id: release_version
        env:
          REF: ${{ github.event.pull_request.ref }}
        run: | 
          VERSION=${REF##*/}
          echo "::set-output name=version::$VERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.release.outputs.version }}
          release_name: ${{ needs.release.outputs.version }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false