name: Create pull request
on:
  push:
jobs:
  pull-request-to-develop:
    name: pull request to develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'create-pr-from-ci'
          base: 'develop'
          title: 'CIからPRを作成'
          body: 'テスト'