name: Release
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  pull-request-to-develop:
    name: pull request to develop
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Pull Request
        uses: actions/github-script@v4
        env:
          BRANCH: ${{ github.head_ref }}
          BODY: ${{ github.event.pull_request.body }}
          VERSION: ${{ steps.release_version.outputs.version }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Merge ${process.env.BRANCH} to develop`,
              body: process.env.BODY,
              head: process.env.BRANCH,
              base: "develop"
            });
  create-release:
    name: Add tag and create github release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Return release version
        id: release_version
        env:
          RELEASE_REF: ${{ github.event.pull_request.head.ref }}
        run: echo ::set-output name=version::${RELEASE_REF#release/}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_version.outputs.version }}
          name: ${{ steps.release_version.outputs.version }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false