name: Release
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  pull-request-to-develop:
    name: pull request to develop
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${ GITHUB_REF#refs/heads/ }
          base: 'develop'
          body: ${{ github.event.pull_request.body }}
  create-release:
    name: Add tag and create github release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Return release version
        id: release_version
        env:
          RELEASE_REF: ${{ github.event.pull_request.head.ref }}
        run: | 
          VERSION=${RELEASE_REF#refs/heads/release/}
          echo "::set-output name=version::$VERSION"
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_version.outputs.version }}
          name: ${{ steps.release_version.outputs.version }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false