on: push

jobs:
  try:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          debug: true
          result-encoding: string
          script: |
            console.log('context.ref', context.ref)
            console.log('github.ref', github.ref)
            const branchName = context.ref
            const releaseVersion = branchName.replace('release/', 'v')
            console.log(branchName, releaseVersion)
            return releaseVersion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}